name: Data Management Zone Deployment

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - infra/*
      - code/*
      - .ado/workflows/dataManagementZoneDeployment.yml
pr:
  branches:
    include:
      - main
  paths:
    include:
      - infra/*
      - code/*
      - .ado/workflows/dataManagementZoneDeployment.yml

variables:
  AZURE_RESOURCE_MANAGER_CONNECTION_NAME: "data-management-zone-service-connection" # Update to '{yourResourceManagerConnectionName}'
  AZURE_SUBSCRIPTION_ID: "17588eb2-2943-461a-ab3f-00a3ceac3112"                     # Update to '{yourDataManagementZoneSubscriptionId}'
  AZURE_LOCATION: "northeurope"                                                     # Update to '{yourRegionName}'

stages:
  - stage: Validation
    displayName: "Validation of IaC templates"
    jobs:
      - job: Validation
        displayName: "Validation of IaC templates"
        continueOnError: false
        pool:
          vmImage: "ubuntu-latest"

        steps:
          # Checkout code
          - checkout: self
            name: checkout_repository
            displayName: Checkout repository
            submodules: true
            lfs: false
            clean: true
            continueOnError: false
            enabled: true

          # Deploy Data Management Zone - validation
          - task: AzureResourceManagerTemplateDeployment@3
            name: data_management_zone_validation
            displayName: Data Management Zone - validation
            enabled: true
            continueOnError: false
            inputs:
              deploymentScope: "Subscription"
              azureResourceManagerConnection: ${{ variables.AZURE_RESOURCE_MANAGER_CONNECTION_NAME }}
              subscriptionId: ${{ variables.AZURE_SUBSCRIPTION_ID }}
              location: ${{ variables.AZURE_LOCATION }}
              templateLocation: "Linked artifact"
              csmFile: "$(System.DefaultWorkingDirectory)/infra/main.json"
              csmParametersFile: "$(System.DefaultWorkingDirectory)/infra/params.dev.json"
              deploymentMode: "Validation"

          # Deploy Data Management Zone - what-if
          - task: AzureCLI@2
            name: data_management_zone_whatif
            displayName: Deploy Data Management Zone - what-if
            enabled: true
            continueOnError: false
            inputs:
              azureSubscription: ${{ variables.AZURE_RESOURCE_MANAGER_CONNECTION_NAME }}
              scriptType: pscore
              scriptLocation: inlineScript
              inlineScript: |
                az account set `
                  --subscription ${{ variables.AZURE_SUBSCRIPTION_ID }}
                
                az deployment sub what-if `
                  --location ${{ variables.AZURE_LOCATION }} `
                  --subscription ${{ variables.AZURE_SUBSCRIPTION_ID }} `
                  --exclude-change-types Ignore NoChange Unsupported `
                  --template-file "$(System.DefaultWorkingDirectory)/infra/main.json" `
                  --parameters "$(System.DefaultWorkingDirectory)/infra/params.dev.json" `
                  --result-format "FullResourcePayloads"
                
              powerShellErrorActionPreference: "stop"
              addSpnToEnvironment: false
              useGlobalConfig: false
              failOnStandardError: false
              powerShellIgnoreLASTEXITCODE: false

  - stage: Deployment
    displayName: "Deployment of IaC templates"
    dependsOn: Validation
    # condition: and(succeeded(), in(variables['Build.Reason'], 'IndividualCI', 'BatchedCI'))
    jobs:
      - job: Deployment
        displayName: "Deployment of IaC templates"
        continueOnError: false
        pool:
          vmImage: "windows-latest"

        steps:
          # Checkout repository
          - checkout: self
            name: checkout_repository
            displayName: "Checkout repository"
            submodules: true
            lfs: false
            clean: true
            continueOnError: false
            enabled: true

          # Deploy Data Management Zone
          - task: AzureResourceManagerTemplateDeployment@3
            name: data_management_zone_deployment
            displayName: Data Management Zone
            enabled: true
            continueOnError: false
            inputs:
              deploymentScope: "Subscription"
              azureResourceManagerConnection: ${{ variables.AZURE_RESOURCE_MANAGER_CONNECTION_NAME }}
              subscriptionId: ${{ variables.AZURE_SUBSCRIPTION_ID }}
              location: ${{ variables.AZURE_LOCATION }}
              templateLocation: "Linked artifact"
              csmFile: "$(System.DefaultWorkingDirectory)/infra/main.json"
              csmParametersFile: "$(System.DefaultWorkingDirectory)/infra/params.dev.json"
              deploymentMode: "Incremental"
